### ISSUE TITLE
Lagging issues with bevy

### ISSUE THREAD

**Issue by lecoqjacob** [rust-gamedev/rust-game-ports#97] opened 2022-06-12 14:35 UTC
Have you noticed a weird lagging issue when moving around in the bevy port? It seems to be linked to the camera movement where the monsters are basically being rendered twice. Here is a gif of it happening [Lagging](https://giphy.com/gifs/LlsO9xTfoXpAKTa3uc)

**Comment by 64kramsystem** [comment] 2022-07-04 23:12
Hi there!

Thanks for the report. For mysterious reasons, I've missed this issue - I've found it by accident :sweat:. Apologies!

I'll check this over the next couple of days, and get back :smile:

**Comment by 64kramsystem** [comment] 2022-07-05 21:56
Damn. I can reproduce it 🤬. I'll debug it; thanks again for the report :smile:

**Comment by 64kramsystem** [comment] 2022-07-05 22:05
Interesting. This is an issue (I'd classify it as bug) also of the source project :exploding_head:.

I'm not sure what's the exact cause. If you stand still and press keys that don't cause movement, the enemies will move, but without this flickering. So it's related, in some way, to the map moving.

**Comment by 64kramsystem** [comment] 2022-07-05 22:38
Bug cause here:

```
map_render at 9,35
entity_render, with offset: 9,35
player_input                       // Player goes left
player moving camera
map_render at 9,34
entity_render, with offset: 9,34   // Enemy drawn with old position in new camera position
map_render at 9,34
entity_render, with offset: 9,34
random_move                        // Enemy moves only now
map_render at 9,34
entity_render, with offset: 9,34   // Enemy drawn with new position in new camera location
player_input
```

it's curious that it also affects also the source project - I haven't checked its logic yet, but there may be a flaw in the state machine.

@lecoqjacob could you confirm that the probem reproduces also for you, on the source project (e.g. from `$repo_path/source_projects/rusty_roguelike/07_TurnBasedGames_02_turnbased`)?

**Comment by 64kramsystem** [comment] 2022-07-05 23:11
Summary: It seems that iyes_loopless ("YL") decides which system (condition) sets will run at the beginning of the frame, so that if the state is changed during one stage, it (YL) doesn't update the plan, and moves Bevy to the next stage. If it's not this, it's something very close.

If this is correct, i sucks big big (big) time - it implies that one can't alter the current flow (in terms of which system sets to run) within one frame.

**Comment by lecoqjacob** [comment] 2022-07-05 23:15
State transitions have always been the downfall of bevy and one of the reasons they are currently rebuilding the entire state management inside of bevy. This issue is one thing preventing me from actually utilizing bevy to make a rogue like. Everything is perfect until you introduce camera movement into the equation

**Comment by lecoqjacob** [comment] 2022-07-05 23:18
@64kramsystem and yes I ran into the issue in the source project first which caused me to abandon the project (hands on rust) and then I found your port and was super excited to try it. Whenever I got to the camera portion, it still happened. 

What would cause this issue even in the source project with legion?

**Comment by 64kramsystem** [comment] 2022-07-05 23:40
> What would cause this issue even in the source project with legion?

Thanks for checking! That's a good question. I haven't had a look at the source project; the bug in the port alone caused me *very* severe hair loss for the last couple of hours.

I think the bug in the source project should be filed to the source project :smile:, since I have the impression that are two different issues, only accidentally happening on two different project (but that's a guess!).

At a very quick check, if you look at the schedules:

```rs
pub fn build_input_scheduler() -> Schedule {
    Schedule::builder()
        .add_system(player_input::player_input_system()) // camera position changed here
        .flush()                                                                                // and flushed here
        .add_system(map_render::map_render_system())
        .add_system(entity_render::entity_render_system()) // enemies are drawn in the same position
        .build()
}

pub fn build_player_scheduler() -> Schedule {
    Schedule::builder()
        .add_system(collisions::collisions_system())
        .flush()
        .add_system(map_render::map_render_system())
        .add_system(entity_render::entity_render_system()) // enemies drawn in the same position again
        .add_system(end_turn::end_turn_system())
        .build()
}

pub fn build_monster_scheduler() -> Schedule {
    Schedule::builder()
        .add_system(random_move::random_move_system()) // now enemies finally move
        .flush()
        .add_system(collisions::collisions_system())
        .flush()
        .add_system(map_render::map_render_system())
        .add_system(entity_render::entity_render_system()) // and here they're rendered in the new position
        .add_system(end_turn::end_turn_system())
        .build()
}
```

you'll see that after the camera moves, the enemies are rendered for at least two frames with the new camera position, but before actually moving.

it's tricky to solve this in the source project (or at least, not trivial), since it renders one schedule per frame.

this is different from the problem that the port suffers, which I describe [here](https://discord.com/channels/691052431525675048/742884593551802431/994021906267242516).

I have the suspicion that this issue may _not_ be fixable in the port (!). If one can't change state (with effect) mid-frame, then the port will need to render one schedule per frame... which will make the port suffer the same problem of the source.

**Comment by 64kramsystem** [comment] 2022-07-05 23:42
He. The source project doesn't accept issues 🤷.

**Comment by 64kramsystem** [comment] 2022-07-06 00:13
Just for reference: this can be fixed in the port, by moving the conditional from the systemset abstraction down to the systems, via simple if/else conditionals.

This is butt-ugly, though, as the conditionals will need to be repeated across all the systems of a system set, and additionally, all the systems will run, and will also be part of the scheduler graph.

**Comment by lecoqjacob** [comment] 2022-07-06 02:37
Yeah I actually tried opening an issue when this arose but didn't have any luck. I thought about reaching out to bracket to see if he had time to check, but he is so busy with life I figured I shouldn't.

Do you plan to put the fix in place for your port or because of the ugliness you rather not?

**Comment by 64kramsystem** [comment] 2022-07-06 08:35
It seems that there is a clean solution :sweat_smile: A teammate pointed me to a [discussion](https://discord.com/channels/691052431525675048/956147241435955203) in a Bevy's channel. Using states may seem intuitively the correct solution (at least, to a non-knowledgeable user (like me)), but it isn't - one needs to use a Resource for that (!). I'll check how this works out and update on this issue :smile:

**Comment by 64kramsystem** [comment] 2022-07-06 09:28
It works. Phew :sweat_smile:

Have a look [here](https://github.com/64kramsystem/rust-game-ports/commit/b703e4b3b7161303048568ec7292a92dbffb6719).

I'm going to take some time to apply the fix to the project, because due to the nature of the Rusty Roguelike port project, I will need to apply this change to approximately 20 workspaces, which may be simple... or not.

In the meanwhile, you can just apply this commit.

**Comment by lecoqjacob** [comment] 2022-07-06 13:07
Amazing news! Also, from what I am reading through the discussions you posted, would Bevy states and scheduler be able to solve the issue iyes_loopless has?

**Comment by 64kramsystem** [comment] 2022-07-06 14:47
> Amazing news! Also, from what I am reading through the discussions you posted, would Bevy states and scheduler be able to solve the issue iyes_loopless has?

AFAIK Bevy's state management is broken. Based on iyes_loopless' author discussion, and what you can see in the branch, using resources instead of state, solves the problem. It's not an issue with iyes_loopless in the sense of a bug, rather, a lack of documentation that makes it not obvious what to use.

**Comment by 64kramsystem** [comment] 2022-07-30 18:14
Closing; this was closed by #112. If you feel like contributing, backporting the fix to the pre-15.02 steps would be great! :smile:

**Closed by 64kramsystem** 2022-07-30 18:14 UTC

**Comment by lecoqjacob** [comment] 2022-07-30 18:23
With the stageless rfc coming ever closer, this stage method to bypass the command flushing will need to be reevaluated. But they plan to add explicit command flushing by then

**Comment by lecoqjacob** [comment] 2022-07-30 18:23
I'll create a pr either today or tomorrow to help with the backfill
